spring:
  datasource:
    d1:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      username: root
      password: root
      type: com.zaxxer.hikari.HikariDataSource

    d2:
      driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@127.0.0.1:1521:ORCL
      username: root
      password: root
      type: com.zaxxer.hikari.HikariDataSource